baseurl = "https://theshamelessdev.com/"
title = "The Shameless Dev"
theme = "casper3"
languageCode = "en-US"
disqusShortname = ""
paginate = 6
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[params]
twitter = "https://twitter.com/devshameless"
github = "https://github.com/theshamelessdev"
description = ""
mainSections = ["post"]

[menu]

[[menu.main]]
identifier = "manifesto"
name = "Manifesto"
url = "/manifesto/"
weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services]

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true
